services:
  nginx:
    image: nginx:stable
    # pull_policy: always
    restart: always
    ports:
      - "80"
      - "443"
    networks:
      nginx-bridge:
      macvlan:
        ipv4_address: "192.168.3.55" #!! consider replacing the value here
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - acme-challenge:/var/www/certbot/:ro
      - letsencrypt:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot
    networks:
      nginx-bridge:
    depends_on:
      - nginx
    volumes:
      - acme-challenge:/var/www/certbot/
      - letsencrypt:/etc/letsencrypt/

volumes:
  acme-challenge:
    name: acme-challenge
  letsencrypt:
    name: letsencrypt

networks:
  nginx-bridge:
    name: nginx-bridge
  macvlan:
    driver: macvlan
    name: macvlan
    external: true

# docker network create -d macvlan \
#     --subnet 192.168.3.0/24 \
#     --gateway 192.168.3.1 \
#     -o parent=eth0 \
#     macvlan
