services:
  nginx:
    image: nginx:stable
    # pull_policy: always
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - acme-challenge:/var/www/certbot/:ro
      - letsencrypt:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - acme-challenge:/var/www/certbot/
      - letsencrypt:/etc/letsencrypt/

volumes:
  acme-challenge:
  letsencrypt:
